export const LoginActionTypes = {
    // User related constants 
     USER_REGISTER_LOADING:"USER_REGISTER_LOADING",
     USER_REGISTER_SUCCESS:"USER_REGISTER_SUCCESS",
     USER_REGISTER_ERROR:"USER_REGISTER_ERROR",
 
     USER_LOGIN_LOADING:"USER_LOGIN_LOADING",
     USER_LOGIN_SUCCESS:"USER_LOGIN_SUCCESS",
     USER_LOGIN_ERROR:"USER_LOGIN_ERROR",
     
     USER_LOGOUT_LOADING:"USER_LOGOUT_LOADING",
     USER_LOGOUT_SUCCESS:"USER_LOGOUT_SUCCESS",
     USER_LOGOUT_ERROR:"USER_LOGOUT_ERROR",
 
     USER_REFRESHTOKEN_LOADING:"USER_REFRESHTOKEN_LOADING",
     USER_REFRESHTOKEN_SUCCESS:"USER_REFRESHTOKEN_SUCCESS",
     USER_REFRESHTOKEN_ERROR:"USER_REFRESHTOKEN_ERROR",

   };
   