export const profileConstants = {
  UPDATE_ADDRESS_LOADING: "UPADTE_ADDRESS_LOADING",
  UPDATE_ADDRESS_ERROR: "UPDATE_ADDRESS_ERROR",
  UPDATE_ADDRESS_SUCCESS: "UPDATE_ADDRESS_SUCCESS",

  GET_ORDERS_LOADING: "GET_ORDERS_LOADING",
  GET_ORDERS_ERROR: "GET_ORDERS_ERROR",
  GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",
};
