export const cartTypes = { 
    // Adding to cart
    ADD_TO_CART_LOADING: "ADD_TO_CART_LOADING",
    ADD_TO_CART_ERROR: "ADD_TO_CART_ERROR",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  
    // Removing from cart
    REMOVE_FROM_CART_LOADING: "REMOVE_FROM_CART_LOADING",
    REMOVE_FROM_CART_ERROR: "REMOVE_FROM_CART_ERROR",
    REMOVE_FROM_CART_SUCCESS: "REMOVE_FROM_CART_SUCCESS",
  
    // Increasing quantity
    INCREASE_QUANTITY_LOADING: "INCREASE_QUANTITY_LOADING",
    INCREASE_QUANTITY_ERROR: "INCREASE_QUANTITY_ERROR",
    INCREASE_QUANTITY_SUCCESS: "INCREASE_QUANTITY_SUCCESS",
  
    // Decreasing quantity
    DECREASE_QUANTITY_LOADING: "DECREASE_QUANTITY_LOADING",
    DECREASE_QUANTITY_ERROR: "DECREASE_QUANTITY_ERROR",
    DECREASE_QUANTITY_SUCCESS: "DECREASE_QUANTITY_SUCCESS",
  };