export const actionTypes = {
   // User related constants 
    USER_REGISTER_LOADING:"USER_REGISTER_LOADING",
    USER_REGISTER_SUCCESS:"USER_REGISTER_SUCCESS",
    USER_REGISTER_ERROR:"USER_REGISTER_ERROR",

    USER_LOGIN_LOADING:"USER_LOGIN_LOADING",
    USER_LOGIN_SUCCESS:"USER_LOGIN_SUCCESS",
    USER_LOGIN_ERROR:"USER_LOGIN_ERROR",
    
    USER_LOGOUT_LOADING:"USER_LOGOUT_LOADING",
    USER_LOGOUT_SUCCESS:"USER_LOGOUT_SUCCESS",
    USER_LOGOUT_ERROR:"USER_LOGOUT_ERROR",

    USER_REFRESHTOKEN_LOADING:"USER_REFRESHTOKEN_LOADING",
    USER_REFRESHTOKEN_SUCCESS:"USER_REFRESHTOKEN_SUCCESS",
    USER_REFRESHTOKEN_ERROR:"USER_REFRESHTOKEN_ERROR",

    // Adding to cart
    ADD_TO_CART_LOADING: "ADD_TO_CART_LOADING",
    ADD_TO_CART_ERROR: "ADD_TO_CART_ERROR",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  
    // Removing from cart
    REMOVE_FROM_CART_LOADING: "REMOVE_FROM_CART_LOADING",
    REMOVE_FROM_CART_ERROR: "REMOVE_FROM_CART_ERROR",
    REMOVE_FROM_CART_SUCCESS: "REMOVE_FROM_CART_SUCCESS",
  
    // Increasing quantity
    INCREASE_QUANTITY_LOADING: "INCREASE_QUANTITY_LOADING",
    INCREASE_QUANTITY_ERROR: "INCREASE_QUANTITY_ERROR",
    INCREASE_QUANTITY_SUCCESS: "INCREASE_QUANTITY_SUCCESS",
  
    // Decreasing quantity
    DECREASE_QUANTITY_LOADING: "DECREASE_QUANTITY_LOADING",
    DECREASE_QUANTITY_ERROR: "DECREASE_QUANTITY_ERROR",
    DECREASE_QUANTITY_SUCCESS: "DECREASE_QUANTITY_SUCCESS",
  };
  